name: Workflow for Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install pytest pytest-cov
      - name: Run tests and collect coverage
        run: python -m pytest --cov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3